export default {
  module: { key: 'module.Reports', label: 'Reportes', order: 4 },
  sections: [
    { key: 'reports.view',   label: 'Ver Reportes',      order: 1 },
    { key: 'reports.export', label: 'Exportar Reportes', order: 2 },
  ],
  actions: [
    { key: 'reports.view.charts',      parent: 'reports.view',   label: 'Gráficos' },
    { key: 'reports.view.breakdown',   parent: 'reports.view',   label: 'Desglose por Categoría' },
    { key: 'reports.view.trends',      parent: 'reports.view',   label: 'Tendencias' },
    // New keys (Paso 2)
    { key: 'reports.view.by_category', parent: 'reports.view',   label: 'Por Categoría' },
    { key: 'reports.view.by_person',   parent: 'reports.view',   label: 'Por Persona' },
    { key: 'reports.view.by_method',   parent: 'reports.view',   label: 'Por Método de Pago' },
    { key: 'reports.view.monthly',     parent: 'reports.view',   label: 'Mensual' },
    { key: 'reports.view.comparative', parent: 'reports.view',   label: 'Comparativa' },
    { key: 'reports.view.detail',      parent: 'reports.view',   label: 'Detalle / Drill-down' },
    { key: 'reports.view.filter',      parent: 'reports.view',   label: 'Filtros y rango de fechas' },

    { key: 'reports.export.pdf',       parent: 'reports.export', label: 'Descargar PDF' },
    { key: 'reports.export.image',     parent: 'reports.export', label: 'Descargar Imagen' },
    // New key (Paso 2)
    { key: 'reports.export.share',     parent: 'reports.export', label: 'Compartir' },
  ],
  defaults: {
    admin: {
      'reports.view':            { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'reports.view.charts':     { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.breakdown':  { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.trends':     { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.by_category':{ can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.by_person':  { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.by_method':  { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.monthly':    { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.comparative':{ can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.detail':     { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.filter':     { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.export':          { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'reports.export.pdf':      { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.export.image':    { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.export.share':    { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
    },
    member: {
      'reports.view':            { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.charts':     { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.breakdown':  { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.trends':     { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.by_category':{ can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.by_person':  { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.by_method':  { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.monthly':    { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.comparative':{ can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.detail':     { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.view.filter':     { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.export':          { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.export.pdf':      { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.export.image':    { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'reports.export.share':    { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: false },
    },
  },
};
