// AUTO-GENERATED — do not edit manually.
// Regenerated by: node scripts/sync-docs-snapshot.mjs
// Last synced: 2026-07-06
// Sources: src/pages/About.jsx + src/pages/UserManual.jsx

export const CURRENT_VERSION_IN_CODE = '2.20.1';

export const VERSION_HISTORY_SNAPSHOT: Array<{ version: string; date: string }> = [
  { version: '2.20.1', date: '2026-07-06' },
  { version: '2.20.0', date: '2026-07-06' },
  { version: '2.19.0', date: '2026-06-29' },
  { version: '2.18.0', date: '2026-06-22' },
  { version: '2.17.0', date: '2026-05-14' },
  { version: '2.16.0', date: '2026-04-28' },
  { version: '2.15.0', date: '2026-04-24' },
  { version: '2.14.0', date: '2026-04-24' },
  { version: '2.13.0', date: '2026-04-22' },
  { version: '2.12.0', date: '2026-04-21' },
  { version: '2.11.0', date: '2026-04-09' },
  { version: '2.10.0', date: '2026-04-08' },
  { version: '2.9.0', date: '2026-04-07' },
  { version: '2.8.0', date: '2026-04-07' },
  { version: '2.7.0', date: '2026-04-07' },
  { version: '2.6.0', date: '2026-04-07' },
  { version: '2.5.0', date: '2026-04-06' },
  { version: '2.4.0', date: '2026-04-06' },
  { version: '2.3.0', date: '2026-04-06' },
  { version: '2.2.0', date: '2026-04-06' },
  { version: '2.1.0', date: '2026-04-06' },
  { version: '2.0.0', date: '2026-04-06' },
  { version: '1.9.0', date: '2026-04-06' },
  { version: '1.8.0', date: '2026-04-06' },
  { version: '1.7.0', date: '2026-04-04' },
  { version: '1.6.0', date: '2026-04-04' },
  { version: '1.5.0', date: '2026-04-03' },
  { version: '1.4.0', date: '2026-04-03' },
  { version: '1.3.0', date: '2026-04-03' },
  { version: '1.2.0', date: '2026-04-02' },
  { version: '1.1.0', date: '2026-03-20' },
  { version: '1.0.0', date: '2026-02-01' },
];

// Number of sections in UserManual.jsx — changes when new docs are added.
export const USER_MANUAL_SECTIONS_COUNT = 25;

// Update this date manually when you review / update UserManual content.
// The daily audit will flag this as stale after 60 days without an update.
export const USER_MANUAL_LAST_REVIEWED = '2026-06-22';

// Git commits since last version tag — used by dailyDocumentationAudit to generate changelog.
export const GIT_LOG_SNAPSHOT = `b7fdeff fix(soporte): desactiva los chips de sugerencia de turnos anteriores
4707e70 security(audit): v2.20.0 — close Trips/Goals nav permission bypass + full release
d0c9ef8 feat(soporte): entrevista IA (BA/PO) para tickets de funcionalidad e incidencia
f50d650 Update base44 packages
f4273b6 fix(lint): quitar import 'UserPlus' sin usar en Register.jsx
8e15ec6 feat(sesiones): AppSession + latido con force-logout + bridge sessions.list/revoke
d33a86c docs: add CLAUDE.md with Base44 functions deploy reminder
b7095a4 fix(functions): make router handlers pass deno lint (no-explicit-any)
add73c1 refactor(functions): consolidate backend functions under 8 routers (94→48 endpoints)
4692891 chore(ci): re-trigger checks (fallo transitorio de runner, sin cambios de código)
14cb1cd feat(soporte): push en tiempo real vía endpoint pull de Mission Control
9d819ce feat(soporte): notifica a Mission Control al crear un ticket (push en tiempo real)
40aac31 security(rls): scope Trip/SupportTicketMessage by declared owner field
df41db2 security(rls): add owner branch to Trip + SupportTicketMessage RLS
14d9094 docs(permissions): regenerate coverage snapshot for Support module
555cfc5 File changes
e86513d File changes
0b0b6f3 Apply RLS security recommendations
2d1a113 Apply RLS security recommendations
09a7aaf File changes
c31107f Update base44 packages
7a1bdb8 security(permissions): close SupportTickets gate + release v2.19.0 (#157)`;
