// AUTO-GENERATED — do not edit manually.
// Regenerated by: node scripts/sync-docs-snapshot.mjs
// Last synced: 2026-08-05
// Sources: src/pages/About.jsx + src/pages/UserManual.jsx

export const CURRENT_VERSION_IN_CODE = '2.21.0';

export const VERSION_HISTORY_SNAPSHOT: Array<{ version: string; date: string }> = [
  { version: '2.21.0', date: '2026-08-05' },
  { version: '2.20.4', date: '2026-08-03' },
  { version: '2.20.3', date: '2026-07-27' },
  { version: '2.20.2', date: '2026-07-06' },
  { version: '2.20.1', date: '2026-07-06' },
  { version: '2.20.0', date: '2026-07-06' },
  { version: '2.19.0', date: '2026-06-29' },
  { version: '2.18.0', date: '2026-06-22' },
  { version: '2.17.0', date: '2026-05-14' },
  { version: '2.16.0', date: '2026-04-28' },
  { version: '2.15.0', date: '2026-04-24' },
  { version: '2.14.0', date: '2026-04-24' },
  { version: '2.13.0', date: '2026-04-22' },
  { version: '2.12.0', date: '2026-04-21' },
  { version: '2.11.0', date: '2026-04-09' },
  { version: '2.10.0', date: '2026-04-08' },
  { version: '2.9.0', date: '2026-04-07' },
  { version: '2.8.0', date: '2026-04-07' },
  { version: '2.7.0', date: '2026-04-07' },
  { version: '2.6.0', date: '2026-04-07' },
  { version: '2.5.0', date: '2026-04-06' },
  { version: '2.4.0', date: '2026-04-06' },
  { version: '2.3.0', date: '2026-04-06' },
  { version: '2.2.0', date: '2026-04-06' },
  { version: '2.1.0', date: '2026-04-06' },
  { version: '2.0.0', date: '2026-04-06' },
  { version: '1.9.0', date: '2026-04-06' },
  { version: '1.8.0', date: '2026-04-06' },
  { version: '1.7.0', date: '2026-04-04' },
  { version: '1.6.0', date: '2026-04-04' },
  { version: '1.5.0', date: '2026-04-03' },
  { version: '1.4.0', date: '2026-04-03' },
  { version: '1.3.0', date: '2026-04-03' },
  { version: '1.2.0', date: '2026-04-02' },
  { version: '1.1.0', date: '2026-03-20' },
  { version: '1.0.0', date: '2026-02-01' },
];

// Number of sections in UserManual.jsx — changes when new docs are added.
export const USER_MANUAL_SECTIONS_COUNT = 25;

// Update this date manually when you review / update UserManual content.
// The daily audit will flag this as stale after 60 days without an update.
export const USER_MANUAL_LAST_REVIEWED = '2026-06-22';

// Git commits since last version tag — used by dailyDocumentationAudit to generate changelog.
export const GIT_LOG_SNAPSHOT = `f55c58b fix(finia): stop emptying the picked FileList before uploading it — THE silent attach bug
fa11358 File changes
9769441 Apply RLS security recommendations
d9cd3c3 feat(finia): capture Cámara photos in-page via getUserMedia, not the OS camera app
6973431 fix(finia): add a clipboard-paste attach button that bypasses Samsung Internet's broken file picker
a6c5db9 fix(finia): detect and recover from a mid-attach page reload, don't stay silent
a4fc4ad fix(finia): split attach into Cámara/Fotos/Archivos to route around Android's file-picker bug
ab706a5 fix(finia): stop silently dropping images picked from phone's Files app
c0a0a35 redesign(scheduled): reorganize into 3 lifecycle tabs + a status filter
3d1655d feat(finia): make image intake actually work, add recurring-charge drafts
c4d26ea fix(scheduled): "Eliminar" no longer no-ops on an already-archived item
f8a4866 feat(scheduled): add a Pausados tab
ec0febb fix(tutorial): stop the setup tutorial from reappearing after skip/complete
f0fe6b0 fix(scheduled): pause/resume actually persists, redesign the card and pause UX
af5e6e8 chore: add boilerplate auth templates
84968c2 design(finia): give the draft card a real signature — a receipt
41589ad fix(finia): make chat smart cards actually smart
3e716a0 redesign(investments): overhaul the pay-registration flow and progress UI
74809d2 fix(investments): stop orphaning a paid installment when the movimiento fails to save
f33dcc9 fix(scheduled): block manual "mark as paid" when it can't create a movimiento
f8e2ac2 fix(docs): correct v2.20.4 deploy scope and cumulative audit summary
5738ccd security(audit): v2.20.4 — periodic review, CI hardening, dependency patch`;
