// AUTO-GENERATED — do not edit manually.
// Regenerated by: node scripts/sync-docs-snapshot.mjs
// Last synced: 2026-07-27
// Sources: src/pages/About.jsx + src/pages/UserManual.jsx

export const CURRENT_VERSION_IN_CODE = '2.20.3';

export const VERSION_HISTORY_SNAPSHOT: Array<{ version: string; date: string }> = [
  { version: '2.20.3', date: '2026-07-27' },
  { version: '2.20.2', date: '2026-07-06' },
  { version: '2.20.1', date: '2026-07-06' },
  { version: '2.20.0', date: '2026-07-06' },
  { version: '2.19.0', date: '2026-06-29' },
  { version: '2.18.0', date: '2026-06-22' },
  { version: '2.17.0', date: '2026-05-14' },
  { version: '2.16.0', date: '2026-04-28' },
  { version: '2.15.0', date: '2026-04-24' },
  { version: '2.14.0', date: '2026-04-24' },
  { version: '2.13.0', date: '2026-04-22' },
  { version: '2.12.0', date: '2026-04-21' },
  { version: '2.11.0', date: '2026-04-09' },
  { version: '2.10.0', date: '2026-04-08' },
  { version: '2.9.0', date: '2026-04-07' },
  { version: '2.8.0', date: '2026-04-07' },
  { version: '2.7.0', date: '2026-04-07' },
  { version: '2.6.0', date: '2026-04-07' },
  { version: '2.5.0', date: '2026-04-06' },
  { version: '2.4.0', date: '2026-04-06' },
  { version: '2.3.0', date: '2026-04-06' },
  { version: '2.2.0', date: '2026-04-06' },
  { version: '2.1.0', date: '2026-04-06' },
  { version: '2.0.0', date: '2026-04-06' },
  { version: '1.9.0', date: '2026-04-06' },
  { version: '1.8.0', date: '2026-04-06' },
  { version: '1.7.0', date: '2026-04-04' },
  { version: '1.6.0', date: '2026-04-04' },
  { version: '1.5.0', date: '2026-04-03' },
  { version: '1.4.0', date: '2026-04-03' },
  { version: '1.3.0', date: '2026-04-03' },
  { version: '1.2.0', date: '2026-04-02' },
  { version: '1.1.0', date: '2026-03-20' },
  { version: '1.0.0', date: '2026-02-01' },
];

// Number of sections in UserManual.jsx — changes when new docs are added.
export const USER_MANUAL_SECTIONS_COUNT = 25;

// Update this date manually when you review / update UserManual content.
// The daily audit will flag this as stale after 60 days without an update.
export const USER_MANUAL_LAST_REVIEWED = '2026-06-22';

// Git commits since last version tag — used by dailyDocumentationAudit to generate changelog.
export const GIT_LOG_SNAPSHOT = `7bd37d9 Update base44 packages
3b080e5 feat(design): unify semantic colors, kill duplicated alert/badge markup, distinguish AI suggestions
5032ab5 fix(scheduled): remove duplicate "domiciliado automático" question
f3f8522 feat(capture): switch toggle for factura + keyboard input on calculator
089dfcc feat(scheduled): add an Automáticos tab for domiciliados automáticos
1611919 fix(maintenance): centralize admin authorization in the router
ec88fa3 chore: stop committing base44/.app.jsonc; use 'base44 link' [base44-migration:app-jsonc-ignored]
9b595a7 Update base44 packages
aa3626a feat(scheduled): collapse paid payments into their own section
7c5a78d fix(family): stop granting platform-admin role on family creation
9a8cf5e test(rls): fail CI when a family-scoped entity's read RLS is admin-only
33e7ec1 fix(rls): restore family-scoped read/write access across core entities
f4977b7 fix(rls): restore family-membership read access on Family/FamilyMembership
2f4e300 Update base44 packages
4343175 style(auth): match rumbo welcome-screen structure on login, keep FlowFin branding
ca28537 Update base44 packages
f7d2b3f security(webhook): validate MP payment id is numeric before outbound fetch (v2.20.2)
d87c2c0 security(functions): gate debug/test maintenance handlers to admin-only (v2.20.1)
6855a70 Update base44 packages
b7fdeff fix(soporte): desactiva los chips de sugerencia de turnos anteriores
4707e70 security(audit): v2.20.0 — close Trips/Goals nav permission bypass + full release
d0c9ef8 feat(soporte): entrevista IA (BA/PO) para tickets de funcionalidad e incidencia`;
