export default {
  module: { key: 'module.Transactions', label: 'Movimientos', order: 2 },
  sections: [
    { key: 'transaction.view',   label: 'Ver Movimientos',    order: 1 },
    { key: 'transaction.create', label: 'Crear Movimiento',   order: 2 },
    { key: 'transaction.edit',   label: 'Editar Movimiento',  order: 3 },
    { key: 'transaction.delete', label: 'Eliminar Movimiento',order: 4 },
    { key: 'transaction.fields', label: 'Edición por Campo',  order: 5 },
  ],
  actions: [
    { key: 'transaction.view.list',         parent: 'transaction.view',   label: 'Listar Movimientos' },
    { key: 'transaction.view.filter',       parent: 'transaction.view',   label: 'Filtrar y Buscar' },
    { key: 'transaction.view.export',       parent: 'transaction.view',   label: 'Exportar a Excel' },
    // New keys (Paso 2)
    { key: 'transaction.view.search',        parent: 'transaction.view',   label: 'Búsqueda' },
    { key: 'transaction.view.pending_banner',parent: 'transaction.view',   label: 'Banner de pendientes' },

    { key: 'transaction.create.manual',     parent: 'transaction.create', label: 'Entrada Manual' },
    { key: 'transaction.create.voice',      parent: 'transaction.create', label: 'Entrada por Voz' },
    { key: 'transaction.create.receipt',    parent: 'transaction.create', label: 'Escanear Ticket' },

    { key: 'transaction.edit.details',      parent: 'transaction.edit',   label: 'Cambiar Detalles' },
    { key: 'transaction.edit.category',     parent: 'transaction.edit',   label: 'Cambiar Categoría' },
    { key: 'transaction.edit.amount',       parent: 'transaction.edit',   label: 'Cambiar Monto' },

    { key: 'transaction.delete.action',     parent: 'transaction.delete', label: 'Eliminar Registro' },

    // Phase 3 — field-level granularity
    { key: 'transaction.fields.amount.edit',         parent: 'transaction.fields', label: 'Editar Monto' },
    { key: 'transaction.fields.date.edit',           parent: 'transaction.fields', label: 'Editar Fecha' },
    { key: 'transaction.fields.category.edit',       parent: 'transaction.fields', label: 'Editar Categoría' },
    { key: 'transaction.fields.person.edit',         parent: 'transaction.fields', label: 'Editar Persona' },
    { key: 'transaction.fields.payment_method.edit', parent: 'transaction.fields', label: 'Editar Forma de Pago' },
    { key: 'transaction.fields.description.edit',    parent: 'transaction.fields', label: 'Editar Descripción' },
    { key: 'transaction.fields.invoice.toggle',      parent: 'transaction.fields', label: 'Toggle Factura' },
  ],
  defaults: {
    admin: {
      'transaction.view':                { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.view.list':           { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'transaction.view.filter':         { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'transaction.view.export':         { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'transaction.view.search':         { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'transaction.view.pending_banner': { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'transaction.create':              { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.create.manual':       { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.create.voice':        { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.create.receipt':      { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.edit':                { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.edit.details':        { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.edit.category':       { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.edit.amount':         { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.delete':              { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.delete.action':       { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.fields':                      { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.fields.amount.edit':          { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.fields.date.edit':            { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.fields.category.edit':        { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.fields.person.edit':          { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.fields.payment_method.edit':  { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.fields.description.edit':     { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
      'transaction.fields.invoice.toggle':       { can_read: true, can_write: true,  can_modify: true,  can_delete: true,  can_view: true },
    },
    member: {
      'transaction.view':                { can_read: true, can_write: true,  can_modify: true,  can_delete: false, can_view: true },
      'transaction.view.list':           { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'transaction.view.filter':         { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'transaction.view.export':         { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'transaction.view.search':         { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'transaction.view.pending_banner': { can_read: true, can_write: false, can_modify: false, can_delete: false, can_view: true },
      'transaction.create':              { can_read: true, can_write: true,  can_modify: false, can_delete: false, can_view: true },
      'transaction.create.manual':       { can_read: true, can_write: true,  can_modify: false, can_delete: false, can_view: true },
      'transaction.create.voice':        { can_read: true, can_write: true,  can_modify: false, can_delete: false, can_view: true },
      'transaction.create.receipt':      { can_read: true, can_write: true,  can_modify: false, can_delete: false, can_view: true },
      'transaction.edit':                { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
      'transaction.edit.details':        { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
      'transaction.edit.category':       { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
      'transaction.edit.amount':         { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
      'transaction.delete':              { can_read: true, can_write: false, can_modify: false, can_delete: true,  can_view: true },
      'transaction.delete.action':       { can_read: true, can_write: false, can_modify: false, can_delete: true,  can_view: true },
      'transaction.fields':                      { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
      'transaction.fields.amount.edit':          { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
      'transaction.fields.date.edit':            { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
      'transaction.fields.category.edit':        { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
      'transaction.fields.person.edit':          { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
      'transaction.fields.payment_method.edit':  { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
      'transaction.fields.description.edit':     { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
      'transaction.fields.invoice.toggle':       { can_read: true, can_write: false, can_modify: true,  can_delete: false, can_view: true },
    },
  },
};
